### ISSUE TITLE
Scroll to top button not working

### ISSUE THREAD

**Issue by OudomMunint** [OudomMunint/Personal-Website#3]
Error:
jquery.js:2 Uncaught Error: Syntax error, unrecognized expression: javascript:
    at fb.error (jquery.js:2:12720)
    at fb.tokenize (jquery.js:2:18599)
    at fb.select (jquery.js:2:21321)
    at Function.fb [as find] (jquery.js:2:7352)
    at m.fn.init.find (jquery.js:2:23595)
    at new m.fn.init (jquery.js:2:24166)
    at m (jquery.js:2:393)
    at HTMLAnchorElement.<anonymous> (all.min.js:62:35)
    at HTMLAnchorElement.dispatch (jquery.js:3:8436)
    at r.handle (jquery.js:3:5139)

**Comment by OudomMunint** [comment]
Fixed back to top functionality but console error still persist
